apiVersion: tekton.dev/v1
kind: Task
metadata:
  creationTimestamp: '2024-11-28T14:54:17Z'
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:steps': {}
          'f:volumes': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2024-11-28T14:54:17Z'
  name: buildah-common
  namespace: overlay-build
  resourceVersion: '4195697'
  uid: e4d25291-ece5-4644-84ca-adf86d5b4868
spec:
  params:
    - default: .
      name: context-dir
      type: string
    - default: Containerfile
      name: containerfile-path
      type: string
    - default: ''
      description: Extra parameters passed for the build command when building images.
      name: BUILD_EXTRA_ARGS
      type: string
  steps:
    - computeResources: {}
      env:
        - name: STORAGE_DRIVER
          value: vfs
        - name: BUILDAH_LAYER
          value: 'true'
      image: 'registry.redhat.io/rhel8/buildah:8.9'
      name: common
      script: |
        #!/bin/bash
        set -Eeuo pipefail
        buildah bud $(params.BUILD_EXTRA_ARGS) -t common:v1 -f $(workspaces.source-workspace.path)/$(params.containerfile-path) $(workspaces.source-workspace.path)/$(params.context-dir)
        buildah push common:v1 oci-archive:/srv/oci-images/common:v1.tar
      securityContext:
        capabilities:
          add:
            - SETFCAP
      volumeMounts:
        - mountPath: /var/lib/containers
          name: container-storage
  volumes:
    - emptyDir: {}
      name: container-storage
  workspaces:
    - description: Workspace containing source code
      name: source-workspace
    - mountPath: /srv/oci-images
      name: oci-images
