apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  creationTimestamp: '2024-11-28T12:49:15Z'
  generation: 7
  managedFields:
    - apiVersion: tekton.dev/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:finally': {}
          'f:params': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2024-11-28T14:34:39Z'
  name: oci-file-shared-workspace
  namespace: overlay-build
  resourceVersion: '4176834'
  uid: b40d3398-d259-49db-8aa8-f8b4e2891ba3
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/andrewdavies-net/overlay-stress-test'
        - name: revision
          value: main
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: 'registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:697b1d12faa0c3ddde73706b304b3c267539bca689ae614815f2186d6befce0b'
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: buildah-common
      params:
        - name: context-dir
          value: .
        - name: containerfile-path
          value: ./build-container/build/Containerfile.s1
        - name: BUILD_EXTRA_ARGS
          value: '--target=common'
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: buildah-common
      workspaces:
        - name: source-workspace
          workspace: shared-workspace
        - name: oci-images
          workspace: oci-images
    - name: buildah-build
      params:
        - name: image-name
          value: 'image-registry.openshift-image-registry.svc:5000/overlay-build/oci-shared:v1'
        - name: context-dir
          value: .
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: containerfile-path
          value: ./build-container/build/Containerfile.s2
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - buildah-common
      taskRef:
        kind: Task
        name: buildah-build
      workspaces:
        - name: oci-images
          workspace: oci-images
        - name: source-workspace
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
    - name: oci-images
