apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-deploy-varlibworkspace
  namespace: overlay-build
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/andrewdavies-net/overlay-stress-test'
        - name: revision
          value: main
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:697b1d12faa0c3ddde73706b304b3c267539bca689ae614815f2186d6befce0b
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: resources
    - name: build-varlib-workspace
      params:
        - name: TLSVERIFY
          value: 'false'
        - name: STORAGE_DRIVER
          value: vfs
        - name: app-dir
          value: /build-container/build/
        - name: containerfile-dir
          value: ./Containerfile
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: build-varlib-workspace
      workspaces:
        - name: files
          workspace: files
        - name: resources
          workspace: resources
  workspaces:
    - name: files
      optional: false
    - name: resources
      optional: false
  params: []
  finally: []
